version: "3.9"

services:
  bot:
    container_name: bot
    build: ./app
    volumes:
      - .:/app
    depends_on:
      - selenium
      - redis
      - postgres
    networks:
      - selenium-network
    restart: always
  worker:
    container_name: worker
    build: ./app
    command: bash /app/app/celery_run.sh
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - .:/app
    depends_on:
      - redis
      - postgres
      - bot
      - selenium
    networks:
      - selenium-network
    restart: always
  beat:
    container_name: beat
    build: ./app
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: bash /app/app/beat_run.sh
    depends_on:
      - redis
      - postgres
      - bot
      - worker
    restart: always
    networks:
      - selenium-network
  redis:
    container_name: redis
    image: redis
    networks:
      - selenium-network
  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - selenium-network
  selenium:
    image: selenium/standalone-chrome:latest
    shm_size: "2gb"
    ports:
      - "4444:4444"
    networks:
      - selenium-network
    environment:
      - TZ=Europe/Moscow

volumes:
  postgres_data:

networks:
  selenium-network:
    driver: bridge
