version: "3.9"

services:
  bot:
    build: ./app
    volumes:
      - .:/app
    depends_on:
      - redis
      - postgres
  worker:
    build: ./app
    command: bash /app/app/celery_run.sh
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - .:/app
    depends_on:
      - redis
      - postgres
      - bot
  beat:
    build: ./app
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: bash /app/app/beat_run.sh
    depends_on:
      - redis
      - postgres
      - bot
      - worker
  redis:
    image: redis
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"

volumes:
  postgres_data:
